//! `ourios-semconv` — generated OpenTelemetry semantic-convention name
//! constants for Ourios's custom metrics and attributes.
//!
//! GENERATED by `weaver registry generate` from the shared
//! `ourios-semconv` registry repo (the ref pinned in
//! `semconv/REGISTRY_REF`). Do not edit by hand: change the registry
//! or the template *in that repo*, bump the pin here, then regenerate
//! (the exact command CI runs — note `--future`, matching
//! `weaver registry check --future`) and commit the result:
//!
//! ```text
//! just semconv-generate   # fetches the pin, runs weaver, formats
//! ```
//!
//! The CI `semconv` job fails if this file drifts from the pinned
//! registry.

#![deny(unsafe_code)]

/// The semantic-conventions schema URL these constants were generated from — the
/// registry manifest's `schema_url`, which carries the conventions version
/// (decoupled from this crate's package version). Mirrors upstream
/// `opentelemetry_semantic_conventions::SCHEMA_URL`; attach it to a telemetry
/// resource so consumers can resolve the schema. Sourced from the registry's
/// resolved provenance (uniform across the registry).
pub const SCHEMA_URL: &str = "https://ourios.dev/schemas/ourios-0.1.0.yaml";

// Metric names (RFC 0009 §3.6).

/// `ourios.audit_sink.buffer.usage` (updowncounter, unit `{event}`).
pub const OURIOS_AUDIT_SINK_BUFFER_USAGE: &str = "ourios.audit_sink.buffer.usage";

/// `ourios.audit_sink.derive.errors` (counter, unit `{error}`).
pub const OURIOS_AUDIT_SINK_DERIVE_ERRORS: &str = "ourios.audit_sink.derive.errors";

/// `ourios.audit_sink.flush.errors` (counter, unit `{error}`).
pub const OURIOS_AUDIT_SINK_FLUSH_ERRORS: &str = "ourios.audit_sink.flush.errors";

/// `ourios.audit_sink.flush.events` (counter, unit `{event}`).
pub const OURIOS_AUDIT_SINK_FLUSH_EVENTS: &str = "ourios.audit_sink.flush.events";

/// `ourios.audit_sink.flushes` (counter, unit `{flush}`).
pub const OURIOS_AUDIT_SINK_FLUSHES: &str = "ourios.audit_sink.flushes";

/// `ourios.auth.resolutions` (counter, unit `{resolution}`).
pub const OURIOS_AUTH_RESOLUTIONS: &str = "ourios.auth.resolutions";

/// `ourios.compaction.backlog` (updowncounter, unit `{partition}`).
pub const OURIOS_COMPACTION_BACKLOG: &str = "ourios.compaction.backlog";

/// `ourios.compaction.duration` (histogram, unit `s`).
pub const OURIOS_COMPACTION_DURATION: &str = "ourios.compaction.duration";

/// `ourios.compaction.files` (counter, unit `{file}`).
pub const OURIOS_COMPACTION_FILES: &str = "ourios.compaction.files";

/// `ourios.compaction.io` (counter, unit `By`).
pub const OURIOS_COMPACTION_IO: &str = "ourios.compaction.io";

/// `ourios.compaction.orphan.files` (counter, unit `{file}`).
pub const OURIOS_COMPACTION_ORPHAN_FILES: &str = "ourios.compaction.orphan.files";

/// `ourios.compaction.partitions` (counter, unit `{partition}`).
pub const OURIOS_COMPACTION_PARTITIONS: &str = "ourios.compaction.partitions";

/// `ourios.compaction.rows` (counter, unit `{row}`).
pub const OURIOS_COMPACTION_ROWS: &str = "ourios.compaction.rows";

/// `ourios.compaction.sweeps` (counter, unit `{sweep}`).
pub const OURIOS_COMPACTION_SWEEPS: &str = "ourios.compaction.sweeps";

/// `ourios.graph.tuples` (counter, unit `{tuple}`).
pub const OURIOS_GRAPH_TUPLES: &str = "ourios.graph.tuples";

/// `ourios.ingest.barrier.captures` (counter, unit `{capture}`).
pub const OURIOS_INGEST_BARRIER_CAPTURES: &str = "ourios.ingest.barrier.captures";

/// `ourios.ingest.barrier.checkpoint.writes` (counter, unit `{write}`).
pub const OURIOS_INGEST_BARRIER_CHECKPOINT_WRITES: &str = "ourios.ingest.barrier.checkpoint.writes";

/// `ourios.ingest.barrier.cuts` (counter, unit `{cut}`).
pub const OURIOS_INGEST_BARRIER_CUTS: &str = "ourios.ingest.barrier.cuts";

/// `ourios.ingest.barrier.epoch` (gauge, unit `{epoch}`).
pub const OURIOS_INGEST_BARRIER_EPOCH: &str = "ourios.ingest.barrier.epoch";

/// `ourios.ingest.barrier.failed_epoch` (gauge, unit `{epoch}`).
pub const OURIOS_INGEST_BARRIER_FAILED_EPOCH: &str = "ourios.ingest.barrier.failed_epoch";

/// `ourios.ingest.barrier.snapshot.writes` (counter, unit `{write}`).
pub const OURIOS_INGEST_BARRIER_SNAPSHOT_WRITES: &str = "ourios.ingest.barrier.snapshot.writes";

/// `ourios.ingest.batches` (counter, unit `{batch}`).
pub const OURIOS_INGEST_BATCHES: &str = "ourios.ingest.batches";

/// `ourios.ingest.encode.queue_depth` (updowncounter, unit `{batch}`).
pub const OURIOS_INGEST_ENCODE_QUEUE_DEPTH: &str = "ourios.ingest.encode.queue_depth";

/// `ourios.ingest.records` (counter, unit `{record}`).
pub const OURIOS_INGEST_RECORDS: &str = "ourios.ingest.records";

/// `ourios.miner.alias.assertions` (counter, unit `{assertion}`).
pub const OURIOS_MINER_ALIAS_ASSERTIONS: &str = "ourios.miner.alias.assertions";

/// `ourios.miner.alias.retractions` (counter, unit `{retraction}`).
pub const OURIOS_MINER_ALIAS_RETRACTIONS: &str = "ourios.miner.alias.retractions";

/// `ourios.miner.body_retention.utilization` (gauge, unit `1`).
pub const OURIOS_MINER_BODY_RETENTION_UTILIZATION: &str = "ourios.miner.body_retention.utilization";

/// `ourios.miner.confidence` (histogram, unit `1`).
pub const OURIOS_MINER_CONFIDENCE: &str = "ourios.miner.confidence";

/// `ourios.miner.confidence.p01` (gauge, unit `1`).
pub const OURIOS_MINER_CONFIDENCE_P01: &str = "ourios.miner.confidence.p01";

/// `ourios.miner.confidence.p50` (gauge, unit `1`).
pub const OURIOS_MINER_CONFIDENCE_P50: &str = "ourios.miner.confidence.p50";

/// `ourios.miner.duration` (histogram, unit `s`).
pub const OURIOS_MINER_DURATION: &str = "ourios.miner.duration";

/// `ourios.miner.merges` (counter, unit `{merge}`).
pub const OURIOS_MINER_MERGES: &str = "ourios.miner.merges";

/// `ourios.miner.params.overflow` (counter, unit `{overflow}`).
pub const OURIOS_MINER_PARAMS_OVERFLOW: &str = "ourios.miner.params.overflow";

/// `ourios.miner.params.overflow.utilization` (gauge, unit `1`).
pub const OURIOS_MINER_PARAMS_OVERFLOW_UTILIZATION: &str =
    "ourios.miner.params.overflow.utilization";

/// `ourios.miner.parse_failures` (counter, unit `{failure}`).
pub const OURIOS_MINER_PARSE_FAILURES: &str = "ourios.miner.parse_failures";

/// `ourios.miner.structured_body.size` (histogram, unit `By`).
pub const OURIOS_MINER_STRUCTURED_BODY_SIZE: &str = "ourios.miner.structured_body.size";

/// `ourios.miner.template.count` (gauge, unit `{template}`).
pub const OURIOS_MINER_TEMPLATE_COUNT: &str = "ourios.miner.template.count";

/// `ourios.miner.template.version_changes` (counter, unit `{change}`).
pub const OURIOS_MINER_TEMPLATE_VERSION_CHANGES: &str = "ourios.miner.template.version_changes";

/// `ourios.miner.upstream_template.processed` (counter, unit `{log_record}`).
pub const OURIOS_MINER_UPSTREAM_TEMPLATE_PROCESSED: &str =
    "ourios.miner.upstream_template.processed";

/// `ourios.query.duration` (histogram, unit `s`).
pub const OURIOS_QUERY_DURATION: &str = "ourios.query.duration";

/// `ourios.query.row_groups` (counter, unit `{row_group}`).
pub const OURIOS_QUERY_ROW_GROUPS: &str = "ourios.query.row_groups";

/// `ourios.query.visibility` (counter, unit `{query}`).
pub const OURIOS_QUERY_VISIBILITY: &str = "ourios.query.visibility";

/// `ourios.receiver.tenant.divergences` (counter, unit `{divergence}`).
pub const OURIOS_RECEIVER_TENANT_DIVERGENCES: &str = "ourios.receiver.tenant.divergences";

/// `ourios.receiver.tls.handshake_failures` (counter, unit `{failure}`).
pub const OURIOS_RECEIVER_TLS_HANDSHAKE_FAILURES: &str = "ourios.receiver.tls.handshake_failures";

/// `ourios.receiver.tls.reload_failures` (counter, unit `{failure}`).
pub const OURIOS_RECEIVER_TLS_RELOAD_FAILURES: &str = "ourios.receiver.tls.reload_failures";

/// `ourios.sink.buffer.usage` (updowncounter, unit `By`).
pub const OURIOS_SINK_BUFFER_USAGE: &str = "ourios.sink.buffer.usage";

/// `ourios.sink.derive.errors` (counter, unit `{error}`).
pub const OURIOS_SINK_DERIVE_ERRORS: &str = "ourios.sink.derive.errors";

/// `ourios.sink.flush.duration` (histogram, unit `s`).
pub const OURIOS_SINK_FLUSH_DURATION: &str = "ourios.sink.flush.duration";

/// `ourios.sink.flush.errors` (counter, unit `{error}`).
pub const OURIOS_SINK_FLUSH_ERRORS: &str = "ourios.sink.flush.errors";

/// `ourios.sink.flush.records` (counter, unit `{record}`).
pub const OURIOS_SINK_FLUSH_RECORDS: &str = "ourios.sink.flush.records";

/// `ourios.storage.parquet.file.size` (histogram, unit `By`).
pub const OURIOS_STORAGE_PARQUET_FILE_SIZE: &str = "ourios.storage.parquet.file.size";

/// `ourios.template_map.artifact.size` (histogram, unit `By`).
pub const OURIOS_TEMPLATE_MAP_ARTIFACT_SIZE: &str = "ourios.template_map.artifact.size";

/// `ourios.template_map.lookups` (counter, unit `{lookup}`).
pub const OURIOS_TEMPLATE_MAP_LOOKUPS: &str = "ourios.template_map.lookups";

/// `ourios.template_map.publishes` (counter, unit `{publish}`).
pub const OURIOS_TEMPLATE_MAP_PUBLISHES: &str = "ourios.template_map.publishes";

/// `ourios.wal.append.duration` (histogram, unit `s`).
pub const OURIOS_WAL_APPEND_DURATION: &str = "ourios.wal.append.duration";

/// `ourios.wal.housekeeping.horizon.remaining` (gauge, unit `{segment}`).
pub const OURIOS_WAL_HOUSEKEEPING_HORIZON_REMAINING: &str =
    "ourios.wal.housekeeping.horizon.remaining";

/// `ourios.wal.housekeeping.unlink.remaining` (gauge, unit `{segment}`).
pub const OURIOS_WAL_HOUSEKEEPING_UNLINK_REMAINING: &str =
    "ourios.wal.housekeeping.unlink.remaining";

/// `ourios.wal.retain_floor.lag.segment.count` (updowncounter, unit `{segment}`).
pub const OURIOS_WAL_RETAIN_FLOOR_LAG_SEGMENT_COUNT: &str =
    "ourios.wal.retain_floor.lag.segment.count";

/// `ourios.wal.retain_floor.lag.size` (updowncounter, unit `By`).
pub const OURIOS_WAL_RETAIN_FLOOR_LAG_SIZE: &str = "ourios.wal.retain_floor.lag.size";

/// `ourios.wal.retain_floor.pinned_tenant.count` (updowncounter, unit `{tenant}`).
pub const OURIOS_WAL_RETAIN_FLOOR_PINNED_TENANT_COUNT: &str =
    "ourios.wal.retain_floor.pinned_tenant.count";

/// `ourios.wal.retain_floor.status` (updowncounter, unit `1`).
pub const OURIOS_WAL_RETAIN_FLOOR_STATUS: &str = "ourios.wal.retain_floor.status";

/// `ourios.wal.rotation.consecutive_failures` (gauge, unit `{failure}`).
pub const OURIOS_WAL_ROTATION_CONSECUTIVE_FAILURES: &str =
    "ourios.wal.rotation.consecutive_failures";

/// `ourios.wal.rotation.status` (updowncounter, unit `1`).
pub const OURIOS_WAL_ROTATION_STATUS: &str = "ourios.wal.rotation.status";

/// `ourios.wal.segment.count` (updowncounter, unit `{segment}`).
pub const OURIOS_WAL_SEGMENT_COUNT: &str = "ourios.wal.segment.count";

/// `ourios.wal.size` (updowncounter, unit `By`).
pub const OURIOS_WAL_SIZE: &str = "ourios.wal.size";

/// `ourios.wal.unflushed.size` (updowncounter, unit `By`).
pub const OURIOS_WAL_UNFLUSHED_SIZE: &str = "ourios.wal.unflushed.size";

/// `ourios.wal.unreclaimed.age` (gauge, unit `s`).
pub const OURIOS_WAL_UNRECLAIMED_AGE: &str = "ourios.wal.unreclaimed.age";

/// `ourios.wal.unreclaimed.size` (updowncounter, unit `By`).
pub const OURIOS_WAL_UNRECLAIMED_SIZE: &str = "ourios.wal.unreclaimed.size";

// Attribute keys.

/// `datafusion.operator.elapsed_compute` attribute key.
pub const DATAFUSION_OPERATOR_ELAPSED_COMPUTE: &str = "datafusion.operator.elapsed_compute";

/// `datafusion.operator.output_bytes` attribute key.
pub const DATAFUSION_OPERATOR_OUTPUT_BYTES: &str = "datafusion.operator.output_bytes";

/// `datafusion.operator.output_rows` attribute key.
pub const DATAFUSION_OPERATOR_OUTPUT_ROWS: &str = "datafusion.operator.output_rows";

/// `datafusion.operator.row_groups_matched` attribute key.
pub const DATAFUSION_OPERATOR_ROW_GROUPS_MATCHED: &str = "datafusion.operator.row_groups_matched";

/// `datafusion.operator.row_groups_pruned` attribute key.
pub const DATAFUSION_OPERATOR_ROW_GROUPS_PRUNED: &str = "datafusion.operator.row_groups_pruned";

/// `log.record.template` attribute key.
pub const LOG_RECORD_TEMPLATE: &str = "log.record.template";

/// `ourios.audit_sink.flush.outcome` attribute key.
pub const OURIOS_AUDIT_SINK_FLUSH_OUTCOME: &str = "ourios.audit_sink.flush.outcome";

/// `ourios.compaction.result` attribute key.
pub const OURIOS_COMPACTION_RESULT: &str = "ourios.compaction.result";

/// `ourios.graph.tuple.operation` attribute key.
pub const OURIOS_GRAPH_TUPLE_OPERATION: &str = "ourios.graph.tuple.operation";

/// `ourios.ingest.barrier.capture.outcome` attribute key.
pub const OURIOS_INGEST_BARRIER_CAPTURE_OUTCOME: &str = "ourios.ingest.barrier.capture.outcome";

/// `ourios.ingest.barrier.cut.outcome` attribute key.
pub const OURIOS_INGEST_BARRIER_CUT_OUTCOME: &str = "ourios.ingest.barrier.cut.outcome";

/// `ourios.ingest.json.lenient` attribute key.
pub const OURIOS_INGEST_JSON_LENIENT: &str = "ourios.ingest.json.lenient";

/// `ourios.io.direction` attribute key.
pub const OURIOS_IO_DIRECTION: &str = "ourios.io.direction";

/// `ourios.miner.parse_failure.reason` attribute key.
pub const OURIOS_MINER_PARSE_FAILURE_REASON: &str = "ourios.miner.parse_failure.reason";

/// `ourios.miner.template_change` attribute key.
pub const OURIOS_MINER_TEMPLATE_CHANGE: &str = "ourios.miner.template_change";

/// `ourios.query.kind` attribute key.
pub const OURIOS_QUERY_KIND: &str = "ourios.query.kind";

/// `ourios.query.row_group.state` attribute key.
pub const OURIOS_QUERY_ROW_GROUP_STATE: &str = "ourios.query.row_group.state";

/// `ourios.query.visibility.branch` attribute key.
pub const OURIOS_QUERY_VISIBILITY_BRANCH: &str = "ourios.query.visibility.branch";

/// `ourios.receiver.template_ids.audit_max` attribute key.
pub const OURIOS_RECEIVER_TEMPLATE_IDS_AUDIT_MAX: &str = "ourios.receiver.template_ids.audit_max";

/// `ourios.receiver.template_ids.data_max` attribute key.
pub const OURIOS_RECEIVER_TEMPLATE_IDS_DATA_MAX: &str = "ourios.receiver.template_ids.data_max";

/// `ourios.receiver.template_ids.files_scanned` attribute key.
pub const OURIOS_RECEIVER_TEMPLATE_IDS_FILES_SCANNED: &str =
    "ourios.receiver.template_ids.files_scanned";

/// `ourios.receiver.template_ids.floor` attribute key.
pub const OURIOS_RECEIVER_TEMPLATE_IDS_FLOOR: &str = "ourios.receiver.template_ids.floor";

/// `ourios.server.listener.name` attribute key.
pub const OURIOS_SERVER_LISTENER_NAME: &str = "ourios.server.listener.name";

/// `ourios.service` attribute key.
pub const OURIOS_SERVICE: &str = "ourios.service";

/// `ourios.sink.flush.trigger` attribute key.
pub const OURIOS_SINK_FLUSH_TRIGGER: &str = "ourios.sink.flush.trigger";

/// `ourios.template.id` attribute key.
pub const OURIOS_TEMPLATE_ID: &str = "ourios.template.id";

/// `ourios.template.version` attribute key.
pub const OURIOS_TEMPLATE_VERSION: &str = "ourios.template.version";

/// `ourios.template_map.lookup.outcome` attribute key.
pub const OURIOS_TEMPLATE_MAP_LOOKUP_OUTCOME: &str = "ourios.template_map.lookup.outcome";

/// `ourios.template_map.publish.outcome` attribute key.
pub const OURIOS_TEMPLATE_MAP_PUBLISH_OUTCOME: &str = "ourios.template_map.publish.outcome";

/// `ourios.tenant` attribute key.
pub const OURIOS_TENANT: &str = "ourios.tenant";

/// `ourios.tenant.watch.first_value` attribute key.
pub const OURIOS_TENANT_WATCH_FIRST_VALUE: &str = "ourios.tenant.watch.first_value";

/// `ourios.tenant.watch.key` attribute key.
pub const OURIOS_TENANT_WATCH_KEY: &str = "ourios.tenant.watch.key";

/// `ourios.tenant.watch.value` attribute key.
pub const OURIOS_TENANT_WATCH_VALUE: &str = "ourios.tenant.watch.value";

/// `ourios.tls.failure` attribute key.
pub const OURIOS_TLS_FAILURE: &str = "ourios.tls.failure";

/// `ourios.tls.listener` attribute key.
pub const OURIOS_TLS_LISTENER: &str = "ourios.tls.listener";

/// `ourios.tls.reload_error` attribute key.
pub const OURIOS_TLS_RELOAD_ERROR: &str = "ourios.tls.reload_error";

/// `ourios.wal.retain_floor.state` attribute key.
pub const OURIOS_WAL_RETAIN_FLOOR_STATE: &str = "ourios.wal.retain_floor.state";

/// `ourios.wal.rotation.state` attribute key.
pub const OURIOS_WAL_ROTATION_STATE: &str = "ourios.wal.rotation.state";

// Log event names (the server's own dogfooded logs; every `tracing` call
// site names its event with one of these — `weaver registry live-check`
// enforces it at emission time).

/// `ourios.compaction.erasure.completed` log event name.
pub const EVENT_OURIOS_COMPACTION_ERASURE_COMPLETED: &str = "ourios.compaction.erasure.completed";

/// `ourios.compaction.sweep.error` log event name.
pub const EVENT_OURIOS_COMPACTION_SWEEP_ERROR: &str = "ourios.compaction.sweep.error";

/// `ourios.graph.backfill.progress` log event name.
pub const EVENT_OURIOS_GRAPH_BACKFILL_PROGRESS: &str = "ourios.graph.backfill.progress";

/// `ourios.querier.shutdown.error` log event name.
pub const EVENT_OURIOS_QUERIER_SHUTDOWN_ERROR: &str = "ourios.querier.shutdown.error";

/// `ourios.receiver.audit_sink.retained` log event name.
pub const EVENT_OURIOS_RECEIVER_AUDIT_SINK_RETAINED: &str = "ourios.receiver.audit_sink.retained";

/// `ourios.receiver.barrier.latched` log event name.
pub const EVENT_OURIOS_RECEIVER_BARRIER_LATCHED: &str = "ourios.receiver.barrier.latched";

/// `ourios.receiver.cadence.join.error` log event name.
pub const EVENT_OURIOS_RECEIVER_CADENCE_JOIN_ERROR: &str = "ourios.receiver.cadence.join.error";

/// `ourios.receiver.publish.held` log event name.
pub const EVENT_OURIOS_RECEIVER_PUBLISH_HELD: &str = "ourios.receiver.publish.held";

/// `ourios.receiver.shutdown.error` log event name.
pub const EVENT_OURIOS_RECEIVER_SHUTDOWN_ERROR: &str = "ourios.receiver.shutdown.error";

/// `ourios.receiver.sink.retained` log event name.
pub const EVENT_OURIOS_RECEIVER_SINK_RETAINED: &str = "ourios.receiver.sink.retained";

/// `ourios.receiver.snapshot.discarded` log event name.
pub const EVENT_OURIOS_RECEIVER_SNAPSHOT_DISCARDED: &str = "ourios.receiver.snapshot.discarded";

/// `ourios.receiver.snapshot.error` log event name.
pub const EVENT_OURIOS_RECEIVER_SNAPSHOT_ERROR: &str = "ourios.receiver.snapshot.error";

/// `ourios.receiver.template_ids.bootstrap.progress` log event name.
pub const EVENT_OURIOS_RECEIVER_TEMPLATE_IDS_BOOTSTRAP_PROGRESS: &str =
    "ourios.receiver.template_ids.bootstrap.progress";

/// `ourios.receiver.template_ids.bootstrapped` log event name.
pub const EVENT_OURIOS_RECEIVER_TEMPLATE_IDS_BOOTSTRAPPED: &str =
    "ourios.receiver.template_ids.bootstrapped";

/// `ourios.receiver.template_ids.refill.failed` log event name.
pub const EVENT_OURIOS_RECEIVER_TEMPLATE_IDS_REFILL_FAILED: &str =
    "ourios.receiver.template_ids.refill.failed";

/// `ourios.receiver.template_ids.refill.stopped` log event name.
pub const EVENT_OURIOS_RECEIVER_TEMPLATE_IDS_REFILL_STOPPED: &str =
    "ourios.receiver.template_ids.refill.stopped";

/// `ourios.receiver.tenant.divergence` log event name.
pub const EVENT_OURIOS_RECEIVER_TENANT_DIVERGENCE: &str = "ourios.receiver.tenant.divergence";

/// `ourios.receiver.tenant.watch_saturated` log event name.
pub const EVENT_OURIOS_RECEIVER_TENANT_WATCH_SATURATED: &str =
    "ourios.receiver.tenant.watch_saturated";

/// `ourios.receiver.wal.checkpoint.error` log event name.
pub const EVENT_OURIOS_RECEIVER_WAL_CHECKPOINT_ERROR: &str = "ourios.receiver.wal.checkpoint.error";

/// `ourios.receiver.wal.housekeeping.error` log event name.
pub const EVENT_OURIOS_RECEIVER_WAL_HOUSEKEEPING_ERROR: &str =
    "ourios.receiver.wal.housekeeping.error";

/// `ourios.receiver.wal.idle_rotation.error` log event name.
pub const EVENT_OURIOS_RECEIVER_WAL_IDLE_ROTATION_ERROR: &str =
    "ourios.receiver.wal.idle_rotation.error";

/// `ourios.receiver.wal.retain_floor.lifted` log event name.
pub const EVENT_OURIOS_RECEIVER_WAL_RETAIN_FLOOR_LIFTED: &str =
    "ourios.receiver.wal.retain_floor.lifted";

/// `ourios.receiver.wal.retain_floor.pinned` log event name.
pub const EVENT_OURIOS_RECEIVER_WAL_RETAIN_FLOOR_PINNED: &str =
    "ourios.receiver.wal.retain_floor.pinned";

/// `ourios.receiver.wal.rotation.recovered` log event name.
pub const EVENT_OURIOS_RECEIVER_WAL_ROTATION_RECOVERED: &str =
    "ourios.receiver.wal.rotation.recovered";

/// `ourios.receiver.wal.rotation.retrying` log event name.
pub const EVENT_OURIOS_RECEIVER_WAL_ROTATION_RETRYING: &str =
    "ourios.receiver.wal.rotation.retrying";

/// `ourios.receiver.wal.rotation.terminal` log event name.
pub const EVENT_OURIOS_RECEIVER_WAL_ROTATION_TERMINAL: &str =
    "ourios.receiver.wal.rotation.terminal";

/// `ourios.receiver.wal.truncated` log event name.
pub const EVENT_OURIOS_RECEIVER_WAL_TRUNCATED: &str = "ourios.receiver.wal.truncated";

/// `ourios.server.auth.open_mode` log event name.
pub const EVENT_OURIOS_SERVER_AUTH_OPEN_MODE: &str = "ourios.server.auth.open_mode";

/// `ourios.server.compaction.disabled` log event name.
pub const EVENT_OURIOS_SERVER_COMPACTION_DISABLED: &str = "ourios.server.compaction.disabled";

/// `ourios.server.graph.list_deadline` log event name.
pub const EVENT_OURIOS_SERVER_GRAPH_LIST_DEADLINE: &str = "ourios.server.graph.list_deadline";

/// `ourios.server.listener.accept.error` log event name.
pub const EVENT_OURIOS_SERVER_LISTENER_ACCEPT_ERROR: &str = "ourios.server.listener.accept.error";

/// `ourios.server.listener.connection.error` log event name.
pub const EVENT_OURIOS_SERVER_LISTENER_CONNECTION_ERROR: &str =
    "ourios.server.listener.connection.error";

/// `ourios.server.signal_handler.error` log event name.
pub const EVENT_OURIOS_SERVER_SIGNAL_HANDLER_ERROR: &str = "ourios.server.signal_handler.error";

/// `ourios.server.tls.plaintext_credentials` log event name.
pub const EVENT_OURIOS_SERVER_TLS_PLAINTEXT_CREDENTIALS: &str =
    "ourios.server.tls.plaintext_credentials";

/// `ourios.server.tls.reload.completed` log event name.
pub const EVENT_OURIOS_SERVER_TLS_RELOAD_COMPLETED: &str = "ourios.server.tls.reload.completed";

/// `ourios.server.tls.reload.error` log event name.
pub const EVENT_OURIOS_SERVER_TLS_RELOAD_ERROR: &str = "ourios.server.tls.reload.error";
