//! RFC 0025 §5 — the storage-owned scenarios: absent-body round-trip
//! (`.1`) and old-file parity (`.2`). Rendering (`.3`) lives in
//! `crates/ourios-querier/tests/rfc0025_rendering.rs`; the sink
//! quarantine (`.4`/`.5`) in
//! `crates/ourios-ingester/tests/rfc0025_quarantine.rs`.
//!
//! The pre-amendment file is the committed
//! `testdata/rfc0025/pre-amendment.parquet` fixture (the RFC 0021 §6
//! committed-fixture discipline), generated by the pre-RFC 0025
//! writer — two ordinals only, no `Absent` rows.

use ourios_core::audit::ParamType;
use ourios_core::record::{BodyKind, MinedRecord, Param};
use ourios_core::tenant::TenantId;
use ourios_parquet::{PartitionKey, Reader, Writer};
use tempfile::TempDir;

/// 2026-04-02T10:58:00Z — the fixture baseline instant.
const TS0: u64 = 1_775_127_480_000_000_000;

fn repo_root() -> std::path::PathBuf {
    std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .and_then(std::path::Path::parent)
        .expect("workspace root")
        .to_path_buf()
}

fn fixture_path() -> std::path::PathBuf {
    repo_root().join("testdata/rfc0025/pre-amendment.parquet")
}

/// A minimal record of each pre-amendment kind, deterministic so the
/// fixture and the parity assertion agree forever.
fn pre_records() -> Vec<MinedRecord> {
    vec![
        // Clean-attach String row (reconstructable shape).
        MinedRecord {
            tenant_id: TenantId::new("rfc0025"),
            template_id: 11,
            template_version: 1,
            severity_number: 9,
            severity_text: Some("INFO".to_string()),
            scope_name: Some("lib.fixture".to_string()),
            scope_version: None,
            scope_attributes: Vec::new(),
            resource_schema_url: None,
            scope_schema_url: None,
            time_unix_nano: TS0,
            observed_time_unix_nano: None,
            attributes: Vec::new(),
            dropped_attributes_count: 0,
            resource_attributes: Vec::new(),
            trace_id: None,
            span_id: None,
            flags: 0,
            event_name: None,
            body_kind: BodyKind::String,
            params: vec![Param {
                type_tag: ParamType::Num,
                value: "7".to_string(),
            }],
            separators: vec![String::new(), " ".to_string()],
            body: None,
            confidence: 1.0,
            lossy_flag: false,
        },
        // Structured row (canonical-JSON body bytes).
        MinedRecord {
            tenant_id: TenantId::new("rfc0025"),
            template_id: 12,
            template_version: 1,
            severity_number: 9,
            severity_text: None,
            scope_name: None,
            scope_version: None,
            scope_attributes: Vec::new(),
            resource_schema_url: None,
            scope_schema_url: None,
            time_unix_nano: TS0 + 1_000,
            observed_time_unix_nano: None,
            attributes: Vec::new(),
            dropped_attributes_count: 0,
            resource_attributes: Vec::new(),
            trace_id: None,
            span_id: None,
            flags: 0,
            event_name: None,
            body_kind: BodyKind::Structured,
            params: Vec::new(),
            separators: Vec::new(),
            body: Some(r#"{"intValue":"42"}"#.to_string()),
            confidence: 1.0,
            // Always false for structured rows (RFC 0001 §6.1) —
            // the body carries canonical JSON, reconstruction is
            // defined.
            lossy_flag: false,
        },
    ]
}

/// An absent-body record as the miner emits it post-RFC 0025:
/// `NO_TEMPLATE`, empty params/separators, `body = None`, and —
/// per §3.1 — `lossy_flag = false` (absence reconstructs exactly,
/// to nothing).
fn absent_record(ts_offset: u64) -> MinedRecord {
    MinedRecord {
        body_kind: BodyKind::Absent,
        template_id: 0,
        template_version: 0,
        time_unix_nano: TS0 + ts_offset,
        body: None,
        params: Vec::new(),
        separators: Vec::new(),
        confidence: 0.0,
        lossy_flag: false,
        ..pre_records().remove(0)
    }
}

/// Scenario RFC0025.1 — absent bodies round-trip.
/// See `docs/rfcs/0025-absent-body-representation.md` §5.
#[test]
fn rfc0025_1_absent_bodies_round_trip() {
    let bucket = TempDir::new().expect("temp dir");
    let originals = vec![
        pre_records().remove(0),
        absent_record(2_000),
        absent_record(3_000),
    ];

    let partition = PartitionKey::derive(&originals[0]).expect("derive");
    let mut writer = Writer::open(bucket.path(), partition.clone()).expect("open writer");
    writer.append_records(&originals).expect("append");
    let written = writer.close().expect("close");

    let reader = Reader::open_partition(&written.path, partition).expect("open_partition");
    let round_tripped = reader.read_all().expect("read_all");

    assert_eq!(round_tripped, originals, "every RFC 0005 §3.2 column");
    for r in round_tripped
        .iter()
        .filter(|r| r.body_kind == BodyKind::Absent)
    {
        assert_eq!(r.body, None, "the body cell is NULL for Absent rows");
        assert!(!r.lossy_flag, "absence is not loss (RFC 0025 §3.1)");
    }
}

/// Scenario RFC0025.2 — old files unaffected.
/// See `docs/rfcs/0025-absent-body-representation.md` §5.
#[test]
fn rfc0025_2_old_files_unaffected() {
    let bucket = TempDir::new().expect("temp dir");
    let partition = PartitionKey::derive(&pre_records()[0]).expect("derive");
    let dir = partition.data_path(bucket.path());
    std::fs::create_dir_all(&dir).expect("mkdir partition");
    std::fs::copy(fixture_path(), dir.join("0-pre-amendment.parquet")).expect(
        "committed fixture missing — regenerate via the ignored rfc0025_fixture test \
         (pre-amendment writer only)",
    );

    let reader = Reader::open_partition(&dir.join("0-pre-amendment.parquet"), partition)
        .expect("open_partition");
    let rows = reader.read_all().expect("read_all");
    assert_eq!(
        rows,
        pre_records(),
        "pre-amendment files read identically under the amended reader",
    );
}

/// Regenerates `testdata/rfc0025/pre-amendment.parquet`. Generated
/// once with the **pre-RFC 0025** writer (two `body_kind` ordinals)
/// and committed; kept for provenance — the rows deliberately avoid
/// `Absent`, so the output is stable across the amendment. Run
/// manually (`cargo test -p ourios-parquet --test rfc0025_absent_body \
/// -- --ignored rfc0025_fixture`); never in CI.
#[test]
#[ignore = "fixture generator — run manually, commit the output"]
fn rfc0025_fixture() {
    let out_dir = fixture_path();
    let out_dir = out_dir.parent().expect("fixture parent");
    std::fs::create_dir_all(out_dir).expect("mkdir testdata/rfc0025");

    let scratch = TempDir::new().expect("temp dir");
    let partition = PartitionKey::derive(&pre_records()[0]).expect("derive");
    let mut writer = Writer::open(scratch.path(), partition).expect("open writer");
    writer.append_records(&pre_records()).expect("append");
    let written = writer.close().expect("close");
    std::fs::copy(&written.path, fixture_path()).expect("install fixture");
    eprintln!("fixture written to {}", fixture_path().display());
}
